apiVersion: v1
kind: Pod
metadata:
  name: cr-rotate
  labels:
    APP_NAME: cr-rotate
spec:
  containers:
  - name: cr-rotate
    image: alpine
    args: [bash]
    workingDir: "/"
    stdin: true
    tty: true
    env:
      - name: GLUU_CONFIG_ADAPTER 
        value: "consul"
      - name: GLUU_CONSUL_HOST 
        value: "localhost"
      - name: GLUU_CONSUL_PORT 
        value: "8500"
      - name: GLUU_CONSUL_CONSISTENCY 
        value: "stale"
      - name: GLUU_CONSUL_SCHEME 
        value: "http"
      - name: GLUU_CONSUL_VERIFY 
        value: "false"
      - name: GLUU_CONSUL_CACERT_FILE 
        value: "/etc/certs/consul_ca.crt"
      - name: GLUU_CONSUL_CERT_FILE 
        value: "/etc/certs/consul_client.crt"
      - name: GLUU_CONSUL_KEY_FILE 
        value: "/etc/certs/consul_client.key"
      - name: GLUU_CONSUL_TOKEN_FILE 
        value: "/etc/certs/consul_token"
      - name: GLUU_KUBERNETES_NAMESPACE 
        value: "default"
      - name: GLUU_KUBERNETES_CONFIGMAP 
        value: "gluu"
      - name: GLUU_CONFIG_ADAPTER
        value: "kubernetes"
      - name: GLUU_SECRET_ADAPTER
        value: "kubernetes"
      - name: GLUU_LDAP_URL
        value: "localhost:1636"
      - name: GLUU_MAX_RAM_FRACTION
        value: "1"
    volumeMounts:
    -  name: cr-rotate
       mountPath: "/root/.kube"
  volumes:
  - name: cr-rotate
    hostPath:
      path: "/root/.kube"
